server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  application:
    name: mq-rabbitmq-template-server
  rabbitmq:
    host: 11.11.11.121
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirm-type: simple #发布确认
    publisher-returns: true #发布返回